name: steve_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  font_awesome_flutter: ^10.12.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/products/

